FROM docker
LABEL maintainer="Amit Kshirsagar <amit.kshirsagar.13@gmail.com>"

RUN apk add --no-cache python
RUN apk add --no-cache py-pip
RUN pip install --upgrade pip
RUN pip install docker-compose
