---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      db: echo
  replicas: 2
  template:
    metadata:
      labels:
        db: echo
    spec:
      volumes:
        - name: echo-pv-storage
          persistentVolumeClaim:
            claimName: echo-pv-claim
      containers:
      - name: echo
        image: gcr.io/google_containers/echoserver:1.4
        volumeMounts:
          - mountPath: "/data"
            name: echo-pv-storage
        resources:
          limits:
            cpu: "0.1"
            memory: "256Mi"
          requests:
            cpu: "0.05"
            memory: "128Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: echo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/opt/data
