FROM jenkins/jnlp-slave:alpine
LABEL maintainer="Amit Kshirsagar <amit.kshirsagar.13@gmail.com>"

USER root
RUN apt install -y curl

USER jenkins

# docker build -t amitkshirsagar13/jenkins-k8s-slave .